/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2022-03-19-a24e6ca"
#endif /* AVUTIL_FFVERSION_H */
